### ISSUE TITLE
Trying to do something similar in JS

### ISSUE THREAD

**Issue by NotDemin** [gingivere0/dalebot#7]
Hey, I've been looking on how I could make a Discord bot that would allow me to interface with the webui and stumbled upon your repo, but the caveat is I want to make it using javascript (Discord.js) and im not that good in python, so I just wanted to ask if you could explain in a few sentences/pseudo code how you're managing to generate the json containing the prompts and sending it to the api, thank !
Im asking cuz ive been trying to send request in postman/js and everytime I get an error and I dont understand why ahah

**Comment by gingivere0** [comment]
I use [PayloadFormatter.py](https://github.com/gingivere0/dalebot/blob/main/PayloadFormatter.py) to construct the json payload format based on the type of request it is. The most simple and common case is if the PayloadFormat is 0 or TXT2IMG. There is a large comment in the do_format() function of that class explaining how the schema is parsed. I parse the schema in this way so that it's generated dynamically, which should make it compatible with all versions of the WebUI. In addition to setting up the payload format, this function modifies indices in the [DataHolder.py](https://github.com/gingivere0/dalebot/blob/main/DataHolder.py) object. These indices indicate where in the json payload to put the prompts. For example, in a standard txt2img request, prompt_ind = 0, meaning that the first item in the payload is going to be the prompt. For a standard txt2img request, the only methods in DataHolder that are called from bot.py are setup() and wordparse(). DataHolder.wordparse() loops through the text of the prompt and looks for parameters, then removes these parameters from from the prompt and sets them according to the corresponding index as it was set in PayloadFormatter.do_format(). 

It's kind of a lot to explain, so if you have any specific questions about what a bit of code does or why it's included, it'd be easier for me to go over it that way than trying to go over the whole thing at once.

Also, if you'd like to post your postman request and response, I may be able to tell you why it's not working

**Comment by NotDemin** [comment]
Sure, i'll post them as soon as i get home, if you want we can take this convo to discord or something to avoid spamming your repo, but thanks for responding tho.

**Comment by NotDemin** [comment]
ok so for your first question, heres an exemple of a request i tried to send in post man :
{
    "fn_index":50,
    "data":[
        "",
        "",
        "None",
        "None",
        20,
        "Euler a",
        false,
        false,
        1,
        1,
        7,
        -1,
        -1,
        0,
        0,
        0,
        false,
        512,
        512,
        false,
        0.7,
        0,
        0,
        "None",
        false,
        false,
        null,
        "",
        "Seed",
        "",
        "Nothing",
        "",
        true,
        false,
        false,
        null,
        "",
        ""
    ],
    "session_hash":"dam7zilr3wt"
}
to api/predict/
I basically just tried to use the networking tab on my browser, but its not working, im getting this as a response : 
{"detail":[{"loc":["body"],"msg":"value is not a valid dict","type":"type_error.dict"}]}

**Comment by NotDemin** [comment]
Ok i managed to make it work, im able to send post requets with my bot now, thanks tho!

**Comment by gingivere0** [comment]
Sorry for the late response, I've been busy the last couple days. Glad you got it working! Let me know if there are any other issues that pop up or bits of my code you'd like me to explain. This is the first big project that I've ever done in Python, so there shouldn't be too much stuff that's specific to Python

**Comment by NotDemin** [comment]
Ahah no problem, thanks for responding, if you want I pushed the code (still in early version) on a repo.
Never figured out why it wasnt working with postman tho
